const mockList = [
    "Lorem Ipsum",
    "Dolor Sit",
    "Consectetur Adipisicing",
    "Amet Elit",
    "Tempora Voluptate",
    "Fugit Doloremque",
    "Quaerat Harum",
    "Assumenda Voluptatem",
    "Aliquam Erat",
    "Vivamus Mollis",
    "Facilisis Lacinia",
    "Egestas Ornare",
    "Nulla Tristique",
    "Gravida Pharetra",
    "Pellentesque Lobortis",
    "Maecenas Eget",
    "Condimentum Elit",
    "Suscipit Porttitor",
    "Vestibulum Mattis",
    "Interdum Fringilla",
    "Efficitur Ultricies",
    "Inceptos Euismod",
    "Habitasse Nunc",
    "Augue Mauris",
    "Pellentesque Nisi",
    "Integer Ante",
    "Vitae Luctus",
    "Porta Ligula",
    "Sollicitudin Orci",
    "Malesuada Pulvinar"
];

export default mockList;
